### ISSUE TITLE
Should add support for controls 

### ISSUE THREAD

**Issue by Dakota628** [Guad/NativeUI#1]
Currently only custom keys can be used. This should either be switched to use custom native controls or both key presses and controls.

**Comment by Guad** [comment]
Originally it used controls, (and it currently uses the arrow key controls) but since the Phone is binded to arrow up by default, I added the Keys. But yeah I'll add custom controls too.

**Comment by Dakota628** [comment]
@Guad Yeah, I'd suggest doing something like I did here. https://github.com/Dakota628/GTAVDeveloperConsole/blob/master/gtav_console/Console/DeveloperConsole.cs#L254

**Comment by Guad** [comment]
@Dakota628 Strange, DisableAllControls did not work at the time for me, but I'll try again.

**Comment by Dakota628** [comment]
Look here: https://github.com/Dakota628/GTAVDeveloperConsole/blob/master/gtav_console/Utils/GTAFuncs.cs#L335

**Comment by Guad** [comment]
@Dakota628 Thanks, that helps

**Comment by Guad** [comment]
Implemented in 9c75cc7a289b12288dbcbd7ffd5b7191ef9f4979

**Comment by Dakota628** [comment]
@Guad 9c75cc7 only checks for a control press on KeyDown, if the player is using a controller or other input device such as a mouse it will not work.

**Comment by Guad** [comment]
@Dakota628 Good call, will fix in the next commit.
