### ISSUE TITLE
Move static methods to a helper class

### ISSUE THREAD

**Issue by Guad** [Guad/NativeUI#10]
Methods like
- DisEnableControls
- GetScreenResolutionMantainRatio
- IsMouseInBounds
- GetSafezoneBounds

Also normalize and make them return integer instead of floats:
- GetScreenResolutionMantainRatio
- GetSafezoneBounds

**Comment by justalemon** [comment]
I'm currently working on this, so far I have:

- [ ] DisEnableControls
- [ ] GetScreenResolutionMantainRatio
- [ ] IsMouseInBounds
- [ ] GetSafezoneBounds
- [ ] GetScreenResolutionMantainRatio
- [ ] GetSafezoneBounds

**Comment by justalemon** [comment]
@Guad Do you think that converting GetScreenResolutionMantainRatio (`Screen.ResolutionMantainRatio`) and GetSafezoneBounds (`Screen.SafezoneBounds`) into `int`s is a good idea? For me, they are for creating accurate screen calculations.

**Comment by Guad** [comment]
Might want to check with 4K and ultrawide screen calculations. If we're losing precision there, just leave them as is.

**Comment by justalemon** [comment]
The changes are now merged and they now comply with backwards compatibility.
