### ISSUE TITLE
Release new version: 1.9

### ISSUE THREAD

**Issue by justalemon** [Guad/NativeUI#104]
There has been [a lot of changes](https://github.com/Guad/NativeUI/compare/1.8...master) since the 1.8 release back on October of 2018, and I feel that we should release 1.9 now.

Because @Guad is the only one with permission to post releases on all of the available platforms (GitHub, 5mods, GTAForums and NuGet), we need your help.

**Comment by Guad** [comment]
Will do it tomorrow :+1:

**Comment by Jaimuzu** [comment]
felipe you epic epic guy......
