### ISSUE TITLE
Description improvements

### ISSUE THREAD

**Issue by karimcambridge** [Guad/NativeUI#105]
First of all, `RecaulculateDescriptionPosition` < ? Name needs to be fixed.

Second of all, stop formatting description constantly, only do it when an item is added the description is changed?

**Comment by justalemon** [comment]
> First of all, RecaulculateDescriptionPosition < ? Name needs to be fixed.

Breaking changes, that says it all.

> stop formatting description constantly

Looks like guad made this while learning, so some parts are just freaking stupid but with some tweaking we can fix it.

**Comment by karimcambridge** [comment]
Talking about someone's code like that in no way motivates people to help you...

**Comment by justalemon** [comment]
>Talking about someone's code like that

I was leaving for school so ended up writing that without thinking, sorry.

What I meant really was that there is a mix between [Ask forgiveness, not permission](https://stackoverflow.com/q/12265451/7620258) and "Let's leave the documentation for later". Usual problems for when you are learning how to code.

> in no way motivates people to help you...

This is GitHub, so...
