### ISSUE TITLE
Menu on top of another, closing submenu

### ISSUE THREAD

**Issue by DGVaniX** [Guad/NativeUI#106]
Hi, so I've noticed that some people are abusing a "glitch" where if I have 2 menus, one on F1, and the other in F2, if you press both of the buttons at the same time, 2 menus will open on top of each other.

Another issue I came across , maybe not an issue of sorts, but I tried to force close the menu when a player is futher than a certain distance from a coord, and if the player has a submenu opened from the menu I try to close, it don't close. (using menu:Visible(false), just so you know)

Any ideos on these 2 things?

**Comment by justalemon** [comment]
> if you press both of the buttons at the same time, 2 menus will open on top of each other.

Maybe close the first one by checking if the second one is open during a tick?

> and if the player has a submenu opened from the menu I try to close, it don't close. (using menu:Visible(false), just so you know)

`SubMenu.Visible = false` or `MenuPool.CloseAllMenus()` should be enough. Otherwise you are maybe doing something wrong.

**Comment by DGVaniX** [comment]
Didn't know about `MenuPool.CloseAllMenus()` but how am I supposed to do check for all the menus? I have like 4 menus in 1 resource with 10+ sub menus, and more menus and submenus in other resources. Not really clean and optimised to do 100+ checks

**Comment by justalemon** [comment]
`MenuPool.IsAnyMenuOpen();`

**Comment by justalemon** [comment]
I'm closing this because the question has already been answered. Feel free to open another issue or reopen the existing one (for more information about the same topic).
