### ISSUE TITLE
Change Menu Font?

### ISSUE THREAD

**Issue by BobbyTheDev** [Guad/NativeUI#107]
Hey I would like to know how to change the menu font, like From cursive to print. Anyone know how to do that?

**Comment by justalemon** [comment]
Where do you want to change the font?

**Comment by BobbyTheDev** [comment]
Where the Text is for the menu. Instead of cursive I can make it print. And how would I change the menu color? Like header, background, etc.?

**Comment by justalemon** [comment]
What? You mean the Title (Native UI) or the Description (NATIVEUI SHOWCASE)?

![image](https://user-images.githubusercontent.com/11861253/55912396-92fdf780-5bb0-11e9-8ef1-e2f862740280.png)

For colors, you can only change the banner colour.

**Comment by Guad** [comment]
UIMenu exposes both `Title` and `Subtitle` which are both `UIResText` objects. You can then change about anything there, e.g.

```
menu.Title.Font = Fonts.ChaletLondon;
```

**Comment by MollyEtFares** [comment]
Hello, sorry to open again the subject but I don't get it how i can change the font of the menu... Which phrase should I change ?

**Comment by Justice219** [comment]
> Hello, sorry to open again the subject but I don't get it how i can change the font of the menu... Which phrase should I change ?


```
// You must have a menu already setup and working currently.
// When that is done make sure you have GTA refferenced

menu.Title.Font = GTA.Font.ChaletLondon; // <-- Change this to whatever
//^ This should be whatever your menu was named!
```
