### ISSUE TITLE
Optimization of UIResText and UIResRectangle

### ISSUE THREAD

**Issue by justalemon** [Guad/NativeUI#108]
So, I'm going to start and rewrite the drawing classes and functions to gain some performance.

The idea is to avoid the calculations of the positions in the Draw() function.

Progress is going to be on the [lemon/optimization](https://github.com/Guad/NativeUI/tree/lemon/optimization) branch.

**Please note that this is not going to generate breaking changes.** I'm going to leave the original classes there but marked as [Obsolete and Errors](https://docs.microsoft.com/en-us/dotnet/api/system.obsoleteattribute.-ctor?view=netframework-4.7.2#System_ObsoleteAttribute__ctor_System_String_System_Boolean_).

**Comment by justalemon** [comment]
@Guad Can you check the NativeText class? In case that I yeeted something.

**Comment by Guad** [comment]
Looks good to me :+1:

**Comment by justalemon** [comment]
@Guad What is the idea behind `AddLongStringForAscii` and `AddLongStringForUtf8`? Why not calling 0x6C188BE134E074AA directly? (`ADD_TEXT_COMPONENT_SUBSTRING_PLAYER_NAME`, previously called `_ADD_TEXT_COMPONENT_STRING`)

**Comment by justalemon** [comment]
This is the NativeUI example running on NativeText without the ports of `AddLongStringForAscii` and `AddLongStringForUtf8`:

![image](https://user-images.githubusercontent.com/11861253/56075176-39522480-5d8c-11e9-98fd-da94cb6e6f8f.png)

@Guad Is 99 the string limit for the function or for all strings on the game?

**Comment by justalemon** [comment]
Because is easier to run quick functions in Python than on C#, I did some testing on the interactive console.

To start, I took the following part of Lorem ipsum and added it as the description of UIMenuItem:

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
```

Then, ran the example to see how many characters words were shown with a single call:

![image](https://user-images.githubusercontent.com/11861253/56076356-25172300-5d9e-11e9-9177-46c8cae94ce8.png)

The word cutted of was labore, so I copied everything from Lorem to labo without the last 2 characters and added them into the Python len function:

```py
>>> x = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labo"
>>> len(x)
97
```

So, 97 characters in total. What about the UTF-8 byte length?

```py
>>> len(x.encode("utf-8"))
97
```

Same, so looks like the total maximum length is 97 and is limited by the game itself.

**Comment by manups4e** [comment]
Fivem found a way to add longer strings

`			API.SetNotificationTextEntry("CELL_EMAIL_BCON");

			foreach (string s in strings)
			{
				API.AddTextComponentSubstringPlayerName(s);
			}`

**Comment by justalemon** [comment]
Yeah, at the end I ended up doing something similar: Dividing the number of characters in the string by 97 and using Math.Ceiling(Result) to get the number of parts that the string needs to be divided.

The only problem is that it needs some tweaking:

![image](https://user-images.githubusercontent.com/11861253/56076862-b4730500-5da3-11e9-8fc6-7899b25cfd60.png)

**Comment by manups4e** [comment]
cool

**Comment by Guad** [comment]
@justalemon IIRC `AddLongStringForUtf8` correctly pushes the 99 UTF8 bytes while `AddLongStringForAscii` incorrectly pushed 99 characters, meaning it could push more than 99 bytes at a time. This is not a problem if the string only contains ASCII characters.
`_ADD_TEXT_COMPONENT_STRING` has a limit of 99 bytes per call. In your example, `FormatDescription` inserted 2 newline characters, so it's 97 lorem ipsum characters + 2 newline characters.

I guess the correct way would be using the `NativeText`'s wordwrap feature and then call the line counting native, but I'm not sure how it works or if it works at all.

**Comment by justalemon** [comment]
After 2 hours, is working without crashing:

![image](https://user-images.githubusercontent.com/11861253/56078588-d70f1900-5db7-11e9-81b6-e63a0d60646a.png)

**Comment by justalemon** [comment]
Currently the following calculations have been moved outside of `Draw()` and `Draw(Size)`:

* Caption Length (Splitted every 90 characters)
* Relative Position
* Word Wrap

**Comment by justalemon** [comment]
Sprite is now NativeSprite, I don't know what is wrong with the calculations on line 49 so I'm going to leave the X and Y calculations on the Tick.

**Comment by justalemon** [comment]
Instead of breaking the compatibility with previous versions, I'm going to move the speed optimizations from the new rewrite branch into master.
