### ISSUE TITLE
UIResText's WordWrap should be int instead of Size

### ISSUE THREAD

**Issue by Guad** [Guad/NativeUI#11]
Since it only uses the width.

**Comment by justalemon** [comment]
Added as part of the new `NativeText` class in #108

**Comment by justalemon** [comment]
This has been added on ae014f08bc802724b95db5f2702e7304f8f2fe62 on the new `NativeText` class. This is going to be closed once the branch is merged on master.

**Comment by justalemon** [comment]
Because #108 went nowhere, I'm doing some minor tweaks on a separate branch. We already have e167860edb2020bc78dc4345408326a72ec3ceff as a fix.
