### ISSUE TITLE
Updated shvdn3 support

### ISSUE THREAD

**Issue by udoprog** [Guad/NativeUI#113]
Just a heads up.

I ported the latest version of NativeUI to ScriptHookV.NET 3 before I realized that there already was a branch for it here.

You can find it here: https://github.com/udoprog/NativeUI/tree/shvdn3

Since this was not based on the existing branch it turned out to be too hard to reconcile the changes, but at least it's up-to-date with the existing master.

Related: crosire/scripthookvdotnet#869

**Comment by justalemon** [comment]
Do you have problem if I push that to this repo?

**Comment by udoprog** [comment]
No problem. That works for me. Thanks <3

**Comment by justalemon** [comment]
Also, regarding crosire/scripthookvdotnet#869. I feel that is not possible to create releases for SHVDN3 because of compatibility issues (v2 vs v3 on the loader) and the non existence of SHVDN3 NuGet packages.

**Comment by udoprog** [comment]
Yeah, I agree. This is on the SHVDN project for now.

**Comment by justalemon** [comment]
The branch shvdn3 has been updated.
