### ISSUE TITLE
Press left or right is to fast.

### ISSUE THREAD

**Issue by Duqino** [Guad/NativeUI#114]
[![Screenshot from Gyazo](https://gyazo.com/fcf641f7fafca987ee6535c829983c71/raw)](https://gyazo.com/fcf641f7fafca987ee6535c829983c71)

That happens when you press only ones on a key. (left or right does not matter)
Thats in the wallet menu. Some how it switches between buttons so damn fast :S 

How can i fix this?

oke the recording program cant even see it. Its like you hit the key 2 times in a millisecond.

Tried in UIMenu LeftPressed and RightPressed -> Citizen.Wait(175)
[![Screenshot from Gyazo](https://gyazo.com/070e0c946aecf4a0c1b38109b50c240b/raw)](https://gyazo.com/070e0c946aecf4a0c1b38109b50c240b)

**Comment by justalemon** [comment]
Hi! We do not maintain the LUA version of NativeUI.

Please open an issue on the correct project repository.
