### ISSUE TITLE
Problems porting Panels

### ISSUE THREAD

**Issue by manups4e** [Guad/NativeUI#115]
Hi.. i'm trying to port panels and other advanced items into Guad's Fivem NativeUI using NativeUI_reloaded as base..

i have a problem on the UpdateParent function in every panel... since Lua is dynamic you can check for not existing parameters without errors (i wish i could in c# too XD) so.. how can port this function in c#? 

```
function UIMenuColourPanel:UpdateParent(Colour)
    local _, ParentType = self.ParentItem()
    if ParentType == "UIMenuListItem" then
        local PanelItemIndex = self.ParentItem:FindPanelItem()
        local PanelIndex = self.ParentItem:FindPanelIndex(self)
        if PanelItemIndex then
            self.ParentItem.Items[PanelItemIndex].Value[PanelIndex] = Colour
            self.ParentItem:Index(PanelItemIndex)
            self.ParentItem.Base.ParentMenu.OnListChange(self.ParentItem.Base.ParentMenu, self.ParentItem, self.ParentItem._Index)
            self.ParentItem.OnListChanged(self.ParentItem.Base.ParentMenu, self.ParentItem, self.ParentItem._Index)
        else
            for Index = 1, #self.ParentItem.Items do
                if type(self.ParentItem.Items[Index]) == "table" then
                    if not self.ParentItem.Items[Index].Panels then
                        self.ParentItem.Items[Index].Panels = {}
                    end
                    self.ParentItem.Items[Index].Panels[PanelIndex] = Colour
                else
                    self.ParentItem.Items[Index] = { Name = tostring(self.ParentItem.Items[Index]), Value = self.ParentItem.Items[Index], Panels = { [PanelIndex] = Colour } }
                end
            end
            self.ParentItem.Base.ParentMenu.OnListChange(self.ParentItem.Base.ParentMenu, self.ParentItem, self.ParentItem._Index)
            self.ParentItem.OnListChanged(self.ParentItem.Base.ParentMenu, self.ParentItem, self.ParentItem._Index)
        end
    elseif ParentType == "UIMenuItem" then
        self.ParentItem.ActivatedPanel(self.ParentItem.ParentMenu, self.ParentItem, self, Colour)
    end
end
```

without this the UIMenuColorPanel will never effect the menu when color is changed

it works on ParentItem.Items... yeah they're dynamic but still typed as string / int / whatever... so the problem is that i can't check into a string value if there's a Panel or add it as it's done here...

**Comment by manups4e** [comment]
everything is working amazingly 
![image](https://user-images.githubusercontent.com/4005518/62004987-e29b0b80-b12c-11e9-83bb-42ea936b9bff.png)

**Comment by manups4e** [comment]
Fixed :) i create a new OnColorChanged event

**Comment by justalemon** [comment]
I really want to see this on NativeUI. Can you please send a Pull Request with this code? If is exclusive to FiveM, I can help to port that.

**Comment by manups4e** [comment]
nono it's not but i don't actually know how to make PRs... if you want i can send you the whole project code (the only thing i've changed parameters around because i've personalized it as my GM needed... nothing changed astronomically that cannot be reverted anytime :)
