### ISSUE TITLE
NativeUI is eating too much resources

### ISSUE THREAD

**Issue by manups4e** [Guad/NativeUI#116]
everytime i open any menu my resmon gets up from 1ms to 3ms.. i think it's a bit too much 😅 is there a way to enhance resources eating?

![image](https://user-images.githubusercontent.com/4005518/62197361-fdb18980-b37f-11e9-8737-c4be909f7240.png)

![image](https://user-images.githubusercontent.com/4005518/62197340-f4c0b800-b37f-11e9-9776-a8a15154edd9.png)

**Comment by manups4e** [comment]
for instance.. i made a static MenuPool variable and i use that only Pool variable for every menu i create in the project

**Comment by justalemon** [comment]
Is not possible because of how terribly optimized FiveM is.

This does not happens on singleplayer by the way.

**Comment by manups4e** [comment]
it might be... actually.. once i open any kind of menu even one without items.. ms raise from 1 (normal) to 3 (10fps loss)

**Comment by justalemon** [comment]
Are you using the FiveM branch?

**Comment by manups4e** [comment]
yeah yeah

**Comment by justalemon** [comment]
Then is related to FIveM. With the master branch and the provided example you don't get any FPS drops in single player.

**Comment by manups4e** [comment]
i see..  :(

**Comment by justalemon** [comment]
How do you open the resource monitor? (I forgot) So I can do some testing from here.

**Comment by manups4e** [comment]
in F8 console, type "resmon 1" to open it and "resmon 0" to close it.. to move the monitor around click on it while F8 console is open

**Comment by manups4e** [comment]
it seems to have fixed itself with a fivem update.. now i get like 1 hitch with the first menu opening.. after that everything go back to normal with any menu opened without ms hitches
