### ISSUE TITLE
MenuPool ProcessKey() Weirdness

### ISSUE THREAD

**Issue by Jackzmc** [Guad/NativeUI#117]
Hello, I'm trying to setup the menu to use the numpad controls.
I had done this for each menucontrol like this:
`Pool.SetKey(UIMenu.MenuControls.Up, Keys.NumPad8);`

But that doesn't press the keys to control the menu, so on the keyDown, I put in:
```cs
Pool.ProcessKey(Keys.NumPad8);
Pool.ProcessKey(Keys.NumPad2);
Pool.ProcessKey(Keys.NumPad5);
Pool.ProcessKey(Keys.NumPad0);
Pool.ProcessKey(Keys.NumPad4);
Pool.ProcessKey(Keys.NumPad6);
```

But this makes the main menu not move, and the submenus it will skip by 6 every time. The UIListItems' will sometimes skip by 6 or 1, and checkboxes will press twice making them pointless.
This does not affect the default arrow key controls, and they work the same. 

And as a side issue, it does not act like the arrow key controls with the sensitivity, it is very sensitive.

**Comment by manups4e** [comment]
use `        public void SetKey(MenuControls control, Control gtaControl)`

**Comment by manups4e** [comment]
SetKey is the right way to do... but Pool is the Menu you're building or the MenuPool? if it's the MenuPool.. try using SetKey directly in the Menu declaration.
Eg: 
```
 UIMenu example = new UIMenu("Example", "Wow this is a description");
 example.SetKey(UIMenu.MenuControls.Up, Keys.NumPad8);
```

**Comment by justalemon** [comment]
Do you have some code that can be used to repro this? I feel that this might be related to the other menu elements.
