### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by Asrielxz** [Guad/NativeUI#118]
I think there is a memory leak with this NativeUI as even when you clear the menu pool the memory used stays high and if you keep making menus and clearing the pool the memory stays high and it can go up to 200 mb used. I tried using garbage collection when the menu pool is cleared but this doesn't help

**Comment by justalemon** [comment]
Do you have a snippet of code that can be used to test this?

If there are memory leaks, it might be CS doing some stupid stuff.

**Comment by manups4e** [comment]
garbage collection is made every tot time by the environment (don't recall how much time passes) you really can control it?
