### ISSUE TITLE
How can I fix this? 

### ISSUE THREAD

**Issue by SHoover80** [Guad/NativeUI#125]
Found new resource NativeUI in C:/FXServer\server-data/resources//NativeUI
Resource loading for NativeUI failed:
Could not open resource metadata file C:/FXServer/server-data/resources//NativeUI/resource.lua.

**Comment by manups4e** [comment]
NativeUI is not a FiveM resource but a library that you can use to build NativeUI menus in C# projects in for FiveM if you need it and resource.lua is not even the correct name for the FiveM manifest as it's name should be __resource.lua
