### ISSUE TITLE
Move the repository into an Organization

### ISSUE THREAD

**Issue by justalemon** [Guad/NativeUI#126]
After the trouble with #99 it feel that is stupid to have completely different versions of NativeUI on the same repo. Because of this, I propose that the repository is moved into a new GitHub organization.

Why? Is easy to have the different versions like this:

* Organization/NativeUI (1.x for SHVDN 2)
* Organization/NativeUI2 (2.x for SHVDN 3)
* Organization/NativeUICFX (2.x for FiveM/CitizenFX)

The final decision needs to be taken by @Guad because he is the owner of the repo.

**Comment by manups4e** [comment]
CitizenFX/NativeUI is already updated and i'd say it's different in many ways from Guad's.. there's no need i'd say to keep Guad's NativeUI with FiveM branch right now..

**Comment by justalemon** [comment]
That is the thing, the FiveM version is a beta experimental version. To make a stable release, we would need to kept the code separate because the calls for the Natives and Game/UI classes are different.

**Comment by Guad** [comment]
Moving this repo to an organization will break the links to it, so I don't feel like it's the right move. While I do agree that it needs to be more separated than a branch, there are better ways to do it. I still think cfx version being under your account & linking to it from the readme as the official cfx fork is good enough.

**Comment by justalemon** [comment]
> Moving this repo to an organization will break the links to it

Nope, it will not. [justalemon/ServerManager](https://github.com/justalemon/ServerManager) was moved and renamed multiple times and ended up at [LambentLight/LambentLight](https://github.com/LambentLight/LambentLight). All of the old links redirect to the new repo.

**Comment by justalemon** [comment]
The other thing that is going to be useful is GitHub Packages for Organizations. With that, we can make NuGet packages available for beta testers without polluting the Public NuGet Repo,

**Comment by Guad** [comment]
> > Moving this repo to an organization will break the links to it
> 
> Nope, it will not. [justalemon/ServerManager](https://github.com/justalemon/ServerManager) was moved and renamed multiple times and ended up at [LambentLight/LambentLight](https://github.com/LambentLight/LambentLight). All of the old links redirect to the new repo.

In that case it seems reasonable. When I find some time I'll make the switch.

**Comment by justalemon** [comment]
For the time being I have create a fork on @RAGENativeUI, so I can start working on a SHVDN 3 version.
