### ISSUE TITLE
how to debug

### ISSUE THREAD

**Issue by yatin6199** [Guad/NativeUI#127]
I am very new to programming i just started right now i facing problem to debug this code.. please tell me how to debug this code..

**Comment by justalemon** [comment]
You can debug NativeUI by launching Grand Theft Auto V via RagePluginHook with the Anti Debugger option enabled. Then, you can just attach the Visual Studio Debugger from Visual Studio.

**Comment by yatin6199** [comment]
> You can debug NativeUI by launching Grand Theft Auto V via RagePluginHook with the Anti Debugger option enabled. Then, you can just attach the Visual Studio Debugger from Visual Studio.

**Comment by yatin6199** [comment]
i have download the rage 

> > You can debug NativeUI by launching Grand Theft Auto V via RagePluginHook with the Anti Debugger option enabled. Then, you can just attach the Visual Studio Debugger from Visual Studio.

 i have downloaded the RagePluginHook and launch  game with it game is successfully  launched but there is no option for anti debugger and i also dont know how to attach the VB debugger to it...
