### ISSUE TITLE
Submenu within a submenu

### ISSUE THREAD

**Issue by Proxximaa** [Guad/NativeUI#128]
Hello, I wanted to create an Addon Spawner menu that is able to have a submenu within a submenu for better categorization of the spawnable vehicles. Due to the lack of information and my lack of coding knowledge i searched if anybody asked the same in here sadly, no. I then moved to the NativeUI reloaded where somebody asked the same question as me well i ran into some issues after that. I now tried to simply use normal nativeui instead of the reloaded which obvs gave me errors i cant solve. The 2 bottom errors where there before aswell as a different version of the top one.

Here is the full code : https://pastr.io/view/BqlnxQX14EF

![image](https://user-images.githubusercontent.com/62262211/77000520-d3d1c500-6958-11ea-80ad-34212007a436.png)

**Comment by justalemon** [comment]
We only maintain the C# version of NativeUI, and you are using the Lua version.

Please, open an issue on the correct repository.
