### ISSUE TITLE
Native UI compatibility for ScriptHookVDotNet3?

### ISSUE THREAD

**Issue by SkyEngine-OSP** [Guad/NativeUI#135]
its been a while since the last release build. So i was thinking would there be plans for ScriptHookVDotNet3 support?

Ta.

**Comment by justalemon** [comment]
At the end I ended up doing my own version of NativeUI as suggested by @Guad under the name LemonUI.

Is a full rewrite of NativeUI that is highly compatible with the existing methods and functions.

It runs on SHVDN 2, SHVDN3, FiveM and RagePluginHook.

If you want to try it yourself, feel free to check [the repository](https://github.com/justalemon/LemonUI) and optionally the [NativeUI Upgrade Instructions](https://github.com/justalemon/LemonUI/wiki/Upgrading-from-NativeUI).

**Comment by justalemon** [comment]
By the way

> I don't really follow GTA5 modding anymore, but I'd say the amount of mods being released is much smaller than before, so not many people would benefit from an incompatible rewrite. So the amount of effort needed is not proportional to the rewards.
> 
> _Originally posted by @Guad in https://github.com/Guad/NativeUI/pull/109#discussion_r280513893_

A lot of people incentivized me to make LemonUI, and there is quite the amount of mods being released or updated to work with LemonUI.

Maybe it might be a good idea to mark NativeUI as a deprecated library, archive the repo and tell people to use LemonUI? I wonder what @Guad thinks about this.

**Comment by SkyEngine-OSP** [comment]
> At the end I ended up doing my own version of NativeUI as suggested by @Guad under the name LemonUI.
> 
> Is a full rewrite of NativeUI that is highly compatible with the existing methods and functions.
> 
> It runs on SHVDN 2, SHVDN3, FiveM and RagePluginHook.
> 
> If you want to try it yourself, feel free to check [the repository](https://github.com/justalemon/LemonUI) and optionally the [NativeUI Upgrade Instructions](https://github.com/justalemon/LemonUI/wiki/Upgrading-from-NativeUI).

This is actually pretty nice. I also found your mod page over at https://gta5-mods.com and i definitely might be utilizing this one if you don't mind. of course, you'll be credited for it.

Thanks a lot!

**Comment by Guad** [comment]
@justalemon Awesome job on the library! Looks much, much better haha. Feel free to add a banner in the readme pointing to your repo.

**Comment by justalemon** [comment]
What about marking the library as deprecated? Both on GitHub (as an archived repo) and NuGet (with LemonUI marked as a replacement)

(if the answer is yes, please don't archive the repo immediately)

**Comment by justalemon** [comment]
cc @Guad

**Comment by Guad** [comment]
yeah sure sounds good. let me know when
