### ISSUE TITLE
I cant define InstructionalButton using ScriptHookVDotNetV3

### ISSUE THREAD

**Issue by dznshfvt** [Guad/NativeUI#137]
I want to create instructional button for my menu, but i get error:

The type 'Control' is defined in an assembly that is not referenced. You must add a reference to assembly 'ScriptHookVDotNet2, Version=2.10.9.0, Culture=neutral, PublicKeyToken=null'

But i need, and i want to use V3, not V2

**Comment by dznshfvt** [comment]
![image](https://user-images.githubusercontent.com/50433345/128689222-57ae01ba-882f-47b4-9102-1d9a66667998.png)
![image](https://user-images.githubusercontent.com/50433345/128689269-0ed021b9-3d9d-4bb5-94c9-15fa1c9fdcd7.png)

**Comment by justalemon** [comment]
NativeUI is no longer updated or supported. Check #136 for more information.
