### ISSUE TITLE
comment l'installer

### ISSUE THREAD

**Issue by iphone59** [Guad/NativeUI#139]
mon menu f5 ne s'affiche pas, je suis novice donc je me demande si je dois installer ce native pour qu'il fonctionne, 
et comment installer ce native, rien n'est indiquer

**Comment by justalemon** [comment]
Bonjour, NativeUI n'est plus pris en charge, vous ne pourrez donc malheureusement pas recevoir d'aide.

Si vous êtes un développeur de logiciels, veuillez effectuer une mise à jour vers LemonUI (https://github.com/LemonUIbyLemon/LemonUI). N'hésitez pas à lire le #136 pour plus d'informations.

Si vous n'êtes pas un développeur et que vous avez été envoyé ici depuis la page d'un mod, veuillez informer le développeur du mod que NativeUI n'est plus pris en charge.

(Je ne connais pas le français, j'ai donc dû utiliser Deepl pour traduire ceci)
