### ISSUE TITLE
How can I format a menu?

### ISSUE THREAD

**Issue by RainerHilmer** [Guad/NativeUI#14]
I cannot find any properties for
- font size of the title
- alignment of the title (left, center)
- width of the menu box
- color of the title box

**Comment by Guad** [comment]
You can access `UIMenu.Title`, which returns a UIResText object.
You can change menu width with `UIMenu.SetMenuWidthOffset`
You can change the color of the title box with `UIMenu.SetBannerType` and use a UIResRectangle.

**Comment by RainerHilmer** [comment]
Okay thank you. :)
