### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LibertyGM** [Guad/NativeUI#142]
Unfortunately, I can't join in. Does not open the list of servers and on the network also does not connect.

Operating System: Arch Linux
KDE Plasma Version: 5.26.4
KDE Frameworks Version: 5.101.0
Qt Version: 5.15.7
Kernel Version: 6.1.1-zen1-1-zen (64-bit)
Graphics Platform: Wayland
Processors: 16 × Intel® Core™ i7-10700K CPU @ 3.80GHz
Memory: 62.7 ГиБ of RAM
Graphics Processor: NVIDIA GeForce RTX 3070 Ti/PCIe/SSE2
Manufacturer: Micro-Star International Co., Ltd.
Product Name: MS-7C80
System Version: 1.0

![Screenshot_20221227_040412](https://user-images.githubusercontent.com/53097257/209596481-7a8a892d-36a9-4507-904d-2a4cf96fd14c.png)

**Comment by justalemon** [comment]
Hi, sorry but NativeUI is no longer supported.

- If you are a user, contact the mod developer and tell them to switch to [LemonUI](https://github.com/LemonUIbyLemon/LemonUI).
- If you are a developer, switch from NativeUI to LemonUI by following the [Upgrading from NativeUI](https://github.com/LemonUIbyLemon/LemonUI/wiki/Upgrading-from-NativeUI) guide
