### ISSUE TITLE
Can you write a NativeUI in C++?

### ISSUE THREAD

**Issue by nustar97** [Guad/NativeUI#143]
Can you write a NativeUI in C++?

**Comment by justalemon** [comment]
Hi!! NativeUI is no longer supported and has been deprecated.

- If you are a user, contact the mod developer and tell them to switch to [LemonUI](https://github.com/LemonUIbyLemon/LemonUI).
- If you are a developer, switch from NativeUI to LemonUI by following the [Upgrading from NativeUI](https://github.com/LemonUIbyLemon/LemonUI/wiki/Upgrading-from-NativeUI) guide
