### ISSUE TITLE
Native UI 

### ISSUE THREAD

**Issue by SpectraX1146** [Guad/NativeUI#144]
This download not have a fxmanifest.lua or resource in it to be able to be used

**Comment by manups4e** [comment]
This is not a fivem API.. you can either look for LemonUI or ScaleformUI for FiveM use

**Comment by justalemon** [comment]
Hi!! NativeUI is no longer supported and has been deprecated.

- If you are a user, contact the mod developer and tell them to switch to [LemonUI](https://github.com/LemonUIbyLemon/LemonUI).
- If you are a developer, switch from NativeUI to LemonUI by following the [Upgrading from NativeUI](https://github.com/LemonUIbyLemon/LemonUI/wiki/Upgrading-from-NativeUI) guide
