### ISSUE TITLE
Assembly File version differs from Latest

### ISSUE THREAD

**Issue by jonjongames1997** [Guad/NativeUI#145]
Is it possible to update the assembly file version number to 1.9.1 instead of 1.9.0? That confuses a lot of people

**Comment by justalemon** [comment]
Hi!! NativeUI is no longer supported and has been deprecated.

- If you are a user, contact the mod developer and tell them to switch to [LemonUI](https://github.com/LemonUIbyLemon/LemonUI).
- If you are a developer, switch from NativeUI to LemonUI by following the [Upgrading from NativeUI](https://github.com/LemonUIbyLemon/LemonUI/wiki/Upgrading-from-NativeUI) guide
