### ISSUE TITLE
Can I pack NativeUI.dll into my mod rar?

### ISSUE THREAD

**Issue by RainerHilmer** [Guad/NativeUI#15]
Hi,
after ScriptHookVDotNet's menu functionality got messed up I switched to NativeUI. Alas the gamers have to download and install another dll now. To make it slightly more convenient for them I'd like to pack the NativeUI.dll along with my mod into the rar which I am about to upload. Do you give permission or do you insist that I just provide the link to here?

**Comment by Guad** [comment]
Sure you could pack it but please state in the description which version you used, and include a link to the thread on gtaforums so people can update when there's a new version available.

**Comment by RainerHilmer** [comment]
Alright but can you give me the link to the GTAforums thread? I came here via the scripthookvdotnet issue tracker where I asked for an alternative menu API.

**Comment by Guad** [comment]
Sure: http://gtaforums.com/topic/809284-net-nativeui/

**Comment by RainerHilmer** [comment]
Thanks :)
