### ISSUE TITLE
No License Intentional?

### ISSUE THREAD

**Issue by lgrahl** [Guad/NativeUI#20]
Is it intentional that you have not chosen a license for this repository?

Citation of [GitHub's documentation about open source licensing](https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license):
> You're under no obligation to choose a license. It's your right not to include one with your code or project, but please be aware of the implications. Generally speaking, the absence of a license means that the default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work. This might not be what you intend.

The reason why I'm asking is that I'm thinking about porting this project to the [Python 3 Script Hook for GTA V](https://github.com/lgrahl/scripthookvpy3k). But without your permission, I have no right to do so (the same applies to many others, of course).

**Comment by Guad** [comment]
I wanted to use a MIT license but I keep forgetting to upload it. I'll do it right now.

**Comment by lgrahl** [comment]
Alright, thanks for the quick reply. :)

**Comment by Guad** [comment]
I've decided with the GPL license.
