### ISSUE TITLE
Show only Subtitle??

### ISSUE THREAD

**Issue by qiangqiang101** [Guad/NativeUI#21]
Image
https://i.ytimg.com/vi/g-seby2Ba5Q/maxresdefault.jpg

**Comment by Guad** [comment]
See No Banners at https://github.com/Guad/NativeUI/wiki/Custom-Banners

**Comment by qiangqiang101** [comment]
Thanks, problem? Solved!
Correction:
var myMenu = new UIMenu("", "Banner-less menu", new Point(0, -107);
var rectangle = new UIResRectangle();
rectangle.Color = Color.FromArgb(0,0,0,0);
myMenu.SetBannerType(rectangle);
