### ISSUE TITLE
May I request ModType ID for Lowrider?

### ISSUE THREAD

**Issue by qiangqiang101** [Guad/NativeUI#22]
May I request ModType ID for Lowrider?

**Comment by Guad** [comment]
Which one

**Comment by qiangqiang101** [comment]
All, the speakers, hydraulics, steering wheels, etc, etc

**Comment by Guad** [comment]
It's the indexes 25-48, try them out.

**Comment by qiangqiang101** [comment]
ok, i'll try, but is there any native to install them on the vehicle? or i just use this VEHICLE::SET_VEHICLE_MOD?

**Comment by Guad** [comment]
Just like any other mod

**Comment by qiangqiang101** [comment]
Thanks it works, but just the dashboard color not working :+1:

**Comment by qiangqiang101** [comment]
@Guad the dashboard color not working

**Comment by Guad** [comment]
It's a separate native, look on gtaforums.

**Comment by qiangqiang101** [comment]
@Guad how to call $F40DD601A65F7F19?

**Comment by qiangqiang101** [comment]
@Guad can you explain which native get the dashboard color, which native set the dashboard color and dial color, lights color, etc tqvm

**Comment by Guad** [comment]
Note that if they don't have the lowrider update (pirated version) the game will crash.


        private int GetInteriorTrimColor(Vehicle veh)
        {
            OutputArgument arg = new OutputArgument();
            if (HasLowriderUpdate)
                Function.Call((Hash) 0x7D1464D472D32136, veh.Handle, arg);
            else
                return 0;
            return arg.GetResult<int>();
        }

        private int GetInteriorDashboardColor(Vehicle veh)
        {
            OutputArgument arg = new OutputArgument();
            if (HasLowriderUpdate)
                Function.Call((Hash) 0xB7635E80A5C31BFF, veh.Handle, arg);
            else
                return 0;
            return arg.GetResult<int>();
        }

**Comment by qiangqiang101** [comment]
Great! I try it once i get home

**Comment by qiangqiang101** [comment]
@Guad 
Type parameter 'T' for 'Public Shared Overloads Function [Call](Of T)(hash As Hash, ParamArray arguments As InputArgument()) As T' cannot be inferred.
Value of type 'Long' cannot be converted to 'Hash'.

my code like this
```
    Public Shared Function GetVehicleInteriorTrimColor(Vehicle As Vehicle) As Integer
        Dim arg As New OutputArgument()
        If My.Settings.HasLowriderUpdate = True Then
            Native.Function.Call(DirectCast(&H7D1464D472D32136L, Hash), Vehicle.Handle, arg)
        Else
            Return 0
        End If
        Return arg.GetResult(Of Integer)()
    End Function
```

**Comment by Guad** [comment]
Sorry, I don't know visual basic.

**Comment by qiangqiang101** [comment]
Alright, thanks a lot!

**Comment by qiangqiang101** [comment]
@Guad after some Trial and Error, i figure it out! Thank you very much!!!
```
    Public Shared Function GetVehicleInteriorTrimColor(Vehicle As Vehicle) As Integer
        Dim arg As New OutputArgument()
        If My.Settings.HasLowriderUpdate = True Then
            Native.Function.Call(&H7D1464D472D32136L, Vehicle.Handle, arg)
        Else
            Return 0
        End If
        Return arg.GetResult(Of Integer)()
    End Function

    Public Shared Function GetVehicleInteriorDashboardColor(Vehicle As Vehicle) As Integer
        Dim arg As New OutputArgument()
        If My.Settings.HasLowriderUpdate = True Then
            Native.Function.Call(&HB7635E80A5C31BFFUL, Vehicle.Handle, arg)
        Else
            Return 0
        End If
        Return arg.GetResult(Of Integer)()
    End Function

        Native.Function.Call(&H6089CDF6A57F326C, _Vehicle.Handle, CInt(ReadCfgValue("DashboardColor", VehicleCfgFile)))
        Native.Function.Call(&HF40DD601A65F7F19UL, _Vehicle.Handle, CInt(ReadCfgValue("TrimColor", VehicleCfgFile)))
```
