### ISSUE TITLE
How can i add text to the right of the UIMenuItem?

### ISSUE THREAD

**Issue by nikita488** [Guad/NativeUI#24]
I want to add text (money count) to the right of the menu item. Like this:
![money_menu_without_color](https://cloud.githubusercontent.com/assets/6237881/12007731/de7ec75c-ac22-11e5-917a-7e267b18f898.png)

**Comment by Guad** [comment]
item.SetRightLabel(string text);

**Comment by nikita488** [comment]
Thanks!
