### ISSUE TITLE
Should add color & opacity switcher

### ISSUE THREAD

**Issue by nikita488** [Guad/NativeUI#25]
I need to create menu with this:
![color bar](https://cloud.githubusercontent.com/assets/6237881/12007735/5e79ded8-ac23-11e5-9bba-60675dab9816.png)
Can you add it?
In the end it should look like this:
![money_menu](https://cloud.githubusercontent.com/assets/6237881/12007739/7e334688-ac23-11e5-9024-9957bb0c0ff2.png)

**Comment by Guad** [comment]
That's very specific, you should do it yourself.

**Comment by nikita488** [comment]
Ok, I'll try. But I think it would be difficult for me :C

**Comment by qiangqiang101** [comment]
I'm looking for something like this too but I want to show the vehicle stat like in LSC.
