### ISSUE TITLE
Example for Big Message please

### ISSUE THREAD

**Issue by qiangqiang101** [Guad/NativeUI#27]
Example for Big Message please

**Comment by Guad** [comment]
It's on the wiki
````
BigMessageThread.MessageInstance.ShowMissionPassedMessage("yo");
````

**Comment by qiangqiang101** [comment]
i tried this: 
```
ShowSimpleShard(string title, string subtitle, int time = 5000)
```
but its not working.

**Comment by Guad** [comment]
Do other ones work? Is there anything in the logs?

**Comment by qiangqiang101** [comment]
i not tested yet, btw #OFFTOPIC how did to show a message (like in community races) after the game properly loaded? because I got an error if i put the code in:
```
Public Sub New()
```
Error: something.something..ctor()
like spawn vehicles and/or objects, but no problem while reload scripts

**Comment by qiangqiang101** [comment]
@Guad seeee

**Comment by frodzet** [comment]
@qiangqiang101 What exactly are you trying to accomplish with that? You don't give us much information and your Error is useless - please post the full error message and a better explanation on what you're trying to accomplish and i might be able to help you :-)

**Comment by qiangqiang101** [comment]
@frodzet what i mean is to spawn ped or object or vehicle on Public sub New() will cause an error, i think its because the game is not properly loaded
but if press insert key to reload the scripts, will not have problem like that.

**Comment by frodzet** [comment]
@qiangqiang101 Did you try putting in a while loop that will wait for the game to fully load before spawning the objects?

**Comment by qiangqiang101** [comment]
@frodzet how can i do that?

**Comment by frodzet** [comment]
// Create a campfire model
            var model = new Model("prop_beach_fire");
            model.Request(250);

            // Check the model is valid
            if (model.IsInCdImage && model.IsValid)
            {
                // Ensure the model is loaded before we try to create it in the world
                while (!model.IsLoaded) Script.Wait(50);

                // Create the prop in the world
                World.CreateProp(model, Game.Player.Character.GetOffsetInWorldCoords(new Vector3(0, 5, 0)), true, true);
            }

            // Mark the model as no longer needed to remove it from memory.
            model.MarkAsNoLongerNeeded();

This is from the ScriptHookVDotNet How To's section, as you can see there is a while(!model.IsLoaded) Script.Wait(50); This basically forces the script to wait processing any further until that specific model is available for usage and once it is it spawns the prop in this case. You can do it with vehicles, peds, etc aswell.

**Comment by qiangqiang101** [comment]
@frodzet OWH, that the problem...
I always use
```
Dim campfire as Prop = World.CreateProp("hashes", Vector3, True, True)
```

**Comment by Guad** [comment]
The problem is you can't call Script.Yield or Script. Wait while the game is loading. You can load them in the tick event as it starts after the player has spawned.

**Comment by frodzet** [comment]
@Guad You can't? So how would he approach what he is trying to accomplish? :-)

**Comment by Guad** [comment]
````
private bool _hasLoaded;
void OnTick(object sender, EventArgs e)
{
    if (!_hasLoaded)
    {
        World.CreateProp(...);
        _hasLoaded = true;
    }
}
````

**Comment by qiangqiang101** [comment]
thank you very much @Guad  @frodzet
