### ISSUE TITLE
Can I only use .png files for UI images?

### ISSUE THREAD

**Issue by sollaholla** [Guad/NativeUI#35]
![capture](https://cloud.githubusercontent.com/assets/14853489/15340340/e59d3b5a-1c56-11e6-84a8-859f6a60ea73.PNG)

I think I did everything right, but it's likely I didn't. I could send over the full code.

**Comment by Guad** [comment]
Yes, only PNG files can be used. That's a ScriptHookV limitation.

**Comment by sollaholla** [comment]
thanks :)

**Comment by sollaholla** [comment]
Still getting the error.

**Comment by Guad** [comment]
Make sure the file actually gets created, and try running the game as admin,

**Comment by sollaholla** [comment]
If I save it to a specific path, does that path have to exist or will it create a new folder?

**Comment by Guad** [comment]
It has to exist

**Comment by sollaholla** [comment]
Could it be because I'm calling it from the constructor?

**Comment by sollaholla** [comment]
*The WriteFileFromResources

**Comment by Guad** [comment]
No. Does the file exist when you check with your file explorer?

**Comment by sollaholla** [comment]
I don't see it appearing, 

```
resourcePath = Sprite.WriteFileFromResources(
                Assembly.GetExecutingAssembly(),
                "TreasureMapGTAV.TM.png", 
                "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Grand Theft Auto V\\scripts\\TM.png");
```

**Comment by Guad** [comment]
Post your log

**Comment by sollaholla** [comment]
```
[18:14:30] [ERROR] Caught fatal unhandled exception:
System.IO.FileNotFoundException: C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V\scripts\TM.png
   at GTA.UI.DrawTexture(String filename, Int32 index, Int32 level, Int32 time, Point pos, PointF center, Size size, Single rotation, Color color, Single aspectRatio)
   at NativeUI.Sprite.DrawTexture(String path, Point position, Size size)
   at TreasureMapGTAV.DrawMap()
   at TreasureMapGTAV.TreasureMapGTAV_Tick(Object sender, EventArgs e)
   at GTA.Script.raise_Tick(Object value0, EventArgs value1)
   at GTA.Script.MainLoop()
```

**Comment by Guad** [comment]
Well either the file is not in your resources, or the path is wrong.

**Comment by sollaholla** [comment]
![capture](https://cloud.githubusercontent.com/assets/14853489/15341400/6a8fc42c-1c5c-11e6-8767-92e1e179d971.PNG)

hmmm.. I copied the path directly from File Explorer, but I could be missing something.
I'll just try the other method. Eventually I'll get it.

**Comment by Guad** [comment]
Show the properties window for the pic

**Comment by sollaholla** [comment]
![capture](https://cloud.githubusercontent.com/assets/14853489/15341529/3432f77c-1c5d-11e6-8511-c85171f37106.PNG)

**Comment by Guad** [comment]
Build Action should be Embedded Resource IIRC

**Comment by sollaholla** [comment]
It worked bro
