### ISSUE TITLE
Sprite.DrawTexture issue

### ISSUE THREAD

**Issue by RaoulWernert** [Guad/NativeUI#37]
When I use the DrawTexture function from Sprite it only shows my texture for what feels like 0.1 second and then removes it for screen.

**Comment by Guad** [comment]
You have to call it every tick

**Comment by RaoulWernert** [comment]
ah right, thanks!

**Comment by RaoulWernert** [comment]
Also when draw text with the Draw function from UiResText after i draw a sprite, the text seems to be behind the sprite. Even through i've drawn the sprite first.

**Comment by Guad** [comment]
That's because DrawTexture uses a DirectX hook, so it always will be on top.

**Comment by RaoulWernert** [comment]
Oh bummer, is there a way to display a long piece of text ontop of an image? like this http://game.rbkdesign.com/images/blog/wow_torture01.jpg

**Comment by Guad** [comment]
You could write text directly on the image with an image manipulation
program

**Comment by RaoulWernert** [comment]
I ment set the text dynamicly so that I can use the same background image but with different text. Just like, let's say how you can set a title for the UIMenu. So that the text is on a, let's say an other layer on top of the image

**Comment by Guad** [comment]
You can't

**Comment by RaoulWernert** [comment]
That's too bad, thanks anyways!
