### ISSUE TITLE
Hide Streetname UI component when instructional buttons are visible

### ISSUE THREAD

**Issue by Guad** [Guad/NativeUI#40]
UI.HideHudComponentThisFrame(HudComponent.StreetName);

**Comment by justalemon** [comment]
What about `HudComponent.AreaName` and `HudComponent.VehicleName`, should those be hidden too?

**Comment by Guad** [comment]
Yeah, probably.

**Comment by justalemon** [comment]
Done, if you want to test it do the following in a tick:
```cs
Game.EnableControlThisFrame(0, GTA.Control.HUDSpecial);
```
