### ISSUE TITLE
menu.ResetKey(UIMenu.MenuControls.Back) blocking pause menu

### ISSUE THREAD

**Issue by mprahlkamps** [Guad/NativeUI#42]
Sorry for opening another issue, but it seems that when I reset the back key, I can't get into the pause menu anymore. Is there anything I have to do for it to work?

Thanks!

**Comment by Guad** [comment]
What do you mean? It shouldn't block anything

**Comment by mprahlkamps** [comment]
When I reset the back key, and I press escape, the official Main menu doesn't open.
In my opinion it should still be accesible.

**Comment by Guad** [comment]
well that's up you to enable. You can do it with Function.Call(Hash.ENABLE_CONTROL_ACTION, 0, (int)Control.FrontendPauseAlternative); after calling menuPool.ProcessMenus();

**Comment by mprahlkamps** [comment]
`Function.Call(Hash.ENABLE_CONTROL_ACTION, 0, (int) GTA.Control.FrontendPauseAlternate, true);`

isn't working for me. Still no main menu popping up.

Any idea why?

**Comment by Guad** [comment]
Make sure it's inside OnTick after your menu processing code. You can also try using `menu.ControlDisablingEnabled = false` then disabling the controls you want yourself.

**Comment by mprahlkamps** [comment]
Cool thanks, `menu.ControlDisablingEnabled = false` did the trick.
I'm not very sure why but it works.

Thanks
