### ISSUE TITLE
ScriptHook.net V3 Compatability

### ISSUE THREAD

**Issue by Tanjitsu** [Guad/NativeUI#49]
Hey,

Im using the latest dev version of scripthook.net which has alot of changes that break NativeUI,
For my own use i made changes to your source to compile with my version of the library.

To save you time, i thought i would post you a copy.
Once the official V3 releases you could just finish off any remaining change.

The comments wouldn't let me attach a zip so ive hosted it on my webserver.
<a href="http://www.151st.co.uk/apps/NativeUI-updated.zip" target="_blank">Download</a>

Regards,
Tanj

**Comment by Guad** [comment]
Hey Tanj,

Thanks a bunch! But we already have a scripthookvdotnet v3 branch, check it
out. Though maybe it's missing some stuff.

**Comment by Tanjitsu** [comment]
`Haha Doh,

Looks like i should have saved my self some time and switched branches :D

Thx Guad !
