### ISSUE TITLE
UIMenuListItem still triggers the event handler when Enabled is set to false

### ISSUE THREAD

**Issue by LeeC2202** [Guad/NativeUI#54]
I have two **UIMenuListItem** entries on a menu and when one of them is set to a certain value, I want to disable the other one as the function of that item is no longer used.

However, if you set **UIMenuListItem.Enabled = false;** all it does is draw the text in grey and continues to change the values and trigger the event handler..

**Enabled = false** should mean don't trigger the event, don't change the values, don't do anything.

**Comment by Guad** [comment]
Should be fixed
