### ISSUE TITLE
move renderingCamera

### ISSUE THREAD

**Issue by twmht** [Guad/NativeUI#57]
Hi all,

I have a function which sets the camera to the sky.

```
        public static void attatchToVeh2(Vehicle veh) {
            Vector3 pos = veh.Position;
            World.DestroyAllCameras();
            Vector3 position = pos;
            float fov = 60.0f;
            Camera camera = World.CreateCamera(position, new Vector3(-90f, 0f, 0f), fov);
            Function.Call(Hash.SET_CAM_INHERIT_ROLL_VEHICLE, camera.Handle, true);

            camera.AttachTo(veh, new Vector3(0f, 0f, 40f));
            camera.IsActive = true;
            World.RenderingCamera = camera;
        }

```

Everything is ok without calling the function via the menu.

When ever I call this function,  when in the menu, it will force the next frame of the camera to the different rotation ( and this is fixed, I can't move).

How can I change the camera rotation while in the menu?

**Comment by Guad** [comment]
Try to disable mouse controls, they should disable any camera changes, even though it only modifies the gameplay camera & not a script one.
