### ISSUE TITLE
Move camera with mouse (like inside los santos custom)

### ISSUE THREAD

**Issue by qiangqiang101** [Guad/NativeUI#6]
Can I move camera with mouse like inside los santos custom?
Becoz i'm currently creating a Premium Deluxe Motorsport in VB so character will be in teleport to a vehicle while in menu. so how to lock the gas, brake, left right turn controls and able to move the camera with mouse?

**Comment by Guad** [comment]
You want to move the camera while in a menu?

**Comment by qiangqiang101** [comment]
Yes
http://img2.wikia.nocookie.net/__cb20130709164827/es.gta/images/9/9e/Los_Santos_Customs.PNG

**Comment by Guad** [comment]
You can use ENABLE_CONTROL_ACTION

**Comment by qiangqiang101** [comment]
not working :(

**Comment by qiangqiang101** [comment]
@Guad 
I want to move the camera like this
https://www.youtube.com/watch?v=Hz5oLpwbm0M
