### ISSUE TITLE
Change menu position

### ISSUE THREAD

**Issue by Anfit5** [Guad/NativeUI#60]
Hello!

How to change menu position on screen? is it even possible??

I've seen that it's already been done using the Network (gtanet.work) using NaiveUI.dll

http://c2n.me/3J9ucMG

**Comment by sollaholla** [comment]
https://github.com/Guad/NativeUI/blob/master/UIMenu.cs#L163

**Comment by Anfit5** [comment]
Okey!
1. if using method **".SetMenuWidthOffset(300)"** in **MenuPool** object -  Menu Title moving to left :(
![titleoffsetbug](https://cloud.githubusercontent.com/assets/26882249/24793179/bdf3a5c0-1b89-11e7-938f-d9d2a95bf842.jpg)

2.if using method **.AddSubMenu**  in **MenuPool** object  - sub menu not inherit main menu positon on screen
![menupostdontinherit](https://cloud.githubusercontent.com/assets/26882249/24793489/e65b01b0-1b8a-11e7-9efc-8b1b78b578a4.jpg)

**Comment by sollaholla** [comment]
You can grab the UIResText object from the menu, and move the title manually. You can also create your own submenu class (derived), and manually set an offset in your constructor, or create a function that does this for you.

**Comment by Bob74** [comment]
Same issue here.
MenuPool.AddSubMenu should support Point() argument to set the offset the same way we create a menu:
```C#
public UIMenu AddSubMenu(UIMenu menu, string text, Point offset)
{
      var item = new UIMenuItem(text);
      menu.AddItem(item);
      var submenu = new UIMenu(menu.Title.Caption, text, offset);
      this.Add(submenu);
      menu.BindMenuToItem(submenu, item);
      return submenu;
}
```
This way, the menu and submenus should be aligned.
