### ISSUE TITLE
text rendering issue with UIMenuListItem

### ISSUE THREAD

**Issue by ejb1123** [Guad/NativeUI#61]
When I use a screen ratio that is not 16:9 **UIMenuListItem** does not properly render the text between the two arrows.
Resolutions tested:
With the Aspect Ratio setting set to auto

| width | height | Works |
| --- | --- | --- |
| 800 | 600 | No |
|1024 | 729 | No |
| 1280 | 600 | No |
| 1280 | 720 | Yes |
| 1280 | 729 | No |
| 1350 | 729 | No |
| 1366 | 768 | Yes|

---

800x600
![image](https://cloud.githubusercontent.com/assets/2042552/25745569/7f68fb1c-316d-11e7-84ca-e4ca9f20c1ee.png "800x600")

**Comment by Guad** [comment]
Could you post your resolution?

**Comment by ejb1123** [comment]
updated the original issue post

**Comment by Guad** [comment]
Just tried it with all those listed and didn't have any issues. It may be an issue with the Fivem port of NativeUI, in which case you'd have to ask them.
![img](https://my.mixtape.moe/tmqaam.PNG)

**Comment by ejb1123** [comment]
Okay I'll contact them and see what the issue is.
