### ISSUE TITLE
MMB for select an item

### ISSUE THREAD

**Issue by MendesKevin** [Guad/NativeUI#63]
Possibility to add the MMB Button (scroll click) for select an item like Arma ?

**Comment by MendesKevin** [comment]
UIMenuPool.SetKey(UIMenu.MenuControls.Select, Keys.MButton);
I said nothing :X

**Comment by Guad** [comment]
You should use a `GTA.Control` instead of a `Key` there, since mouse doesnt trigger OnKeyDown events IIRC

**Comment by MendesKevin** [comment]
Yep i see that :)

Thank you for your job and good continuation
