### ISSUE TITLE
UIMenuItem extra properties (Sub Item)?

### ISSUE THREAD

**Issue by qiangqiang101** [Guad/NativeUI#7]
Currently have Text, Description, can we have extra field?
for Example I need to read a list of item from a database

Example Database:
.Text     .SetRightLabel      .SubItem(index)
AK47   |   $7000    |    ak47ModelNameHere
MG6    |   $12000  |    mg6ModelNameHere

**Comment by Guad** [comment]
Use a Dictionary<string, WeaponHash>? or WeaponHash.TryParse

**Comment by qiangqiang101** [comment]
i donno, just for example

**Comment by qiangqiang101** [comment]
oops wrong press

**Comment by qiangqiang101** [comment]
hello

**Comment by Guad** [comment]
I think that's unnecessary. If you want to hold data, use a list, dictionary or whatever you want.
