### ISSUE TITLE
Using in-game texture for banner

### ISSUE THREAD

**Issue by Starystars67** [Guad/NativeUI#72]
Hi i seem to have an issue with your latest release see below:
![image](https://user-images.githubusercontent.com/15389482/30969465-5d3999d8-a45a-11e7-9c6e-237771100632.png)
i was testing this in the example menu, here is my code: 
![image](https://user-images.githubusercontent.com/15389482/30969487-6dd65e8e-a45a-11e7-9c9c-4a318ef95761.png)

thanks for any help you can give :)

P.S Amazing work!!!

**Comment by Guad** [comment]
add `using System.Drawing;` to the top of your script, and add System.Drawing.dll to your project references.

**Comment by Starystars67** [comment]
Tried that and it returns this: 
![image](https://user-images.githubusercontent.com/15389482/30969980-dc54f504-a45b-11e7-9cd9-5f40b8f8de64.png)

**Comment by Guad** [comment]
Try adding this to the top of your script
```
using Size = System.Drawing.Size;
using Point = System.Drawing.Point;
```

**Comment by Starystars67** [comment]
Nope still same result

**Comment by Guad** [comment]
You should contact CitizenFX developers then.

**Comment by Starystars67** [comment]
Okay, will post back with what happens for future reference.

**Comment by Starystars67** [comment]
Solution: 
To fix this for now for future reference do what is in the accepted answer here:
https://stackoverflow.com/questions/517058/how-to-reference-a-namespace-from-a-specific-assembly
Then change new Point to something like new SysDraw.Point(0, 0) and then the same for Size. SysDraw is what i changed System.Drawing's Aliases to instead of global.

Thanks for your time @Guad :) and again nice work!

**Comment by Starystars67** [comment]
Would you be able to help with this?
I am trying to set the banner, no compiler errors are thrown but it does not display the banner (shopui_title_barber). here is my code am i missing something?
`public MenuExample()
    {
        _menuPool = new MenuPool();
        var mainMenu = new UIMenu("", "NATIVEUI SHOWCASE");
        var banner = new Sprite("shopui_title_carmod", "shopui_title_carmod", new SysDraw.Point(0, 0), new SysDraw.Size(0, 0));
        _menuPool.SetBannerType(banner);
        _menuPool.Add(mainMenu);
        AddMenuKetchup(mainMenu);
        AddMenuFoods(mainMenu);
        AddMenuCook(mainMenu);
        AddMenuAnotherMenu(mainMenu);
        _menuPool.RefreshIndex();

		Tick += new Func<Task>(async delegate
		{
            _menuPool.ProcessMenus();
			if (Game.IsControlJustReleased(1, Control.MultiplayerInfo) || Game.IsControlJustPressed(1, Control.VehicleHorn)) // Our menu on/off switch
			{
                mainMenu.Visible = !mainMenu.Visible;
			}
            await Task.FromResult(0);
		});
	}`

**Comment by Guad** [comment]
switch these lines around
```
_menuPool.SetBannerType(banner);
_menuPool.Add(mainMenu);
```

so it should look like this
```
_menuPool.Add(mainMenu);
_menuPool.SetBannerType(banner);
```

**Comment by Starystars67** [comment]
Amazing thanks mate 5*
