### ISSUE TITLE
directx texture 

### ISSUE THREAD

**Issue by marhex** [Guad/NativeUI#8]
when i use this
 mainMenu = new UIMenu("CRIME LIFE", "~r~by Marhex");
mainMenu.SetBannerType(Sprite.WriteFileFromResources(Assembly.GetExecutingAssembly(), "team_fight.image.png"));
_menuPool.Add(mainMenu);

i get this error
[16:58:08] CORE: Creating texture 'C:\Users\heythem\AppData\Local\Temp\tmpD6A8.tmp', id 0
[16:58:08] FATAL: directx texture 'C:\Users\heythem\AppData\Local\Temp\tmpD6A8.tmp' creation failed

**Comment by Guad** [comment]
1. Make sure your picture is an embedded resource. Click on it in the Solution Explorer and make sure Build Action property is set to Embedded Resource
2. Make sure you wrote the path right, it should be DefaultNamespace.yourImage.png
You can get your default namespace in your project properties.

**Comment by marhex** [comment]
thenks it work
