### ISSUE TITLE
Using External Image For Banner

### ISSUE THREAD

**Issue by Tyler-Abel** [Guad/NativeUI#80]
I am trying to add an external image for my banner. Here are my calling references
_using System;
using System.Collections.Generic;
using System.Drawing;
using Size = System.Drawing.Size;
using Point = System.Drawing.Point;
using System.Windows.Forms;
using System.Linq;
using System.Text;
using GTA;
using GTA.Native;
using NativeUI;_

And here is the code I have at my banner
__menuPool = new MenuPool();
var mainMenu = new UIMenu("RSA", "~y~Mod by Abel Gaming and AlexBoosted");
 _menuPool.Add(mainMenu);
 _menuPool.SetBannerType("scripts\\RSA-Banner.png");
RoadSideServices(mainMenu);
RentalServices(mainMenu);
TravelServices(mainMenu);
 _menuPool.RefreshIndex();_

I am getting the following errors:
![bandicam 2018-08-21 00-46-35-284](https://user-images.githubusercontent.com/20889064/44380869-b9650a80-a4db-11e8-8b8a-32e86124d40f.jpg)

**Comment by Guad** [comment]
In your project add a reference to ScriptHookDotNet.dll
