### ISSUE TITLE
Spelling correction on public function will break mod compatibility.

### ISSUE THREAD

**Issue by LeeC2202** [Guad/NativeUI#86]
It would appear that the spelling of GetScreenResolutionMantainRatio() has been changed to GetScreenResolutionMaintainRatio(). This simple change will break any mods that call that function... like Map Editor. (Yes, despite all the grief ME gets in some circles, some of us still use it, because some of us appreciate that you did the object placement correctly... i.e. objects keep their rotation when you move the camera. :-) This is a massive time-saver for placing objects in a uniform direction. And that you can export in C# code... kudos to you for those choices. :thumbsup: )

Might be worth adding a redirect in there to ensure compatibility, as some mod authors have long since abandoned their mods. I know it's messy in the source but most people won't see it. Just something as simple as:

public static SizeF GetScreenResolutionMantainRatio()
{
	return GetScreenResolutionMaintainRatio();
}

**Comment by Guad** [comment]
I thought the obsolete `GetScreenResolutionMantainRatio` introduced in #53 was still in the codebase but it seems I accidently removed it in #62 
I'll add it back in, thanks for the heads up

**Comment by Guad** [comment]
Fixed in 624517d
