### ISSUE TITLE
Adding discount icons (red %)

### ISSUE THREAD

**Issue by justalemon** [Guad/NativeUI#88]
I wonder if is possible to add the % discount icons like in GTA Online:

![image](https://user-images.githubusercontent.com/11861253/49701418-ec3a2800-fbca-11e8-95ba-8a25fc31cc8e.png)

If so, how?

**Comment by Guad** [comment]
Look for the texture name and add it here:
https://github.com/Guad/NativeUI/blob/master/Items/UIMenuItem.cs#L252
