### ISSUE TITLE
Are you looking for new contributors?

### ISSUE THREAD

**Issue by justalemon** [Guad/NativeUI#96]
As @Guad might have seen, I have sent most of the Pull Requests since of june of last year. I use NativeUI on most of my projects because of how easy is to use for both users and developers.

Because there has not been a lot of activity on the repo, I want to become a Full Time [Collaborator](https://help.github.com/articles/inviting-collaborators-to-a-personal-repository/) of the project. To keep it alive and updated.

If @Guad wants to talk privately, I can be found on:

* Discord: Lemon#6947
* Steam: [Here](https://steamcommunity.com/profiles/76561198118215221/)
* E-Mail: lemon@justalemon.ml

**Comment by Guad** [comment]
Thank you for the work you have done! I've added you as a collaborator.

**Comment by justalemon** [comment]
Thanks man! I'm still going to create Pull Requests because of the new addition of [WIP/Draft PRs on GitHub](https://github.blog/2019-02-14-introducing-draft-pull-requests/).
