### ISSUE TITLE
NuGet packages are shared between the example and library

### ISSUE THREAD

**Issue by justalemon** [Guad/NativeUI#97]
When you edit a NuGet package on `NativeUI.csproj`, it also gets updated on `MenuExample.csproj` but without the changes on the References.

This only affects developers.

**Comment by justalemon** [comment]
I'm currently separating the NativeUI project from the example so is ordered and they don't collide with each other.

@Guad do you think that is a good idea? They are on the [lemon/file-order](https://github.com/Guad/NativeUI/tree/lemon/file-order) branch.

**Comment by Guad** [comment]
Yeah that's way cleaner 👍

**Comment by justalemon** [comment]
83bfc9ae22fb80ae0045aab17536be6f144726ea fixes this.
