### ISSUE TITLE
"Official" FiveM version of NativeUI

### ISSUE THREAD

**Issue by justalemon** [Guad/NativeUI#99]
To avoid more those FiveM copies lying around on the internet, I have created an "Official" FiveM version of NativeUI. Is currently on the [fivem](https://github.com/Guad/NativeUI/tree/fivem) branch and it requires some additional setup.

Until we decide for a way to release this version, there are some specific steps and requirements.

First, you need some prerequisites:

* [Git command line](https://git-scm.com/downloads) or a Git GUI that supports adding submodules (for example, [GitKraken](https://www.gitkraken.com))
* [Visual Studio 2017](https://visualstudio.microsoft.com/) (the Community edition is fine) or the [NuGet command line](https://www.nuget.org/downloads)

#### If using the Git command line
Run the following command **from your project folder** to add NativeUI as a submodule:

```sh
git submodule add -b fivem https://github.com/Guad/NativeUI.git NativeUI
```

#### If using a Git GUI
Check the documentation for your specific Git GUI.

### Adding the NativeUI project
On Visual Studio, right click your Solution and select `Add > Existing project...` and search for `NativeUI\NativeUI\NativeUI.csproj`. Once found, double click it.

#### With Visual Studio 2017
Right Click the NativeUI project and select `Manage NuGet Packages...`. Then, you should see `Some NuGet packages are missing...`. Click the Restore button.

#### With the NuGet CLI
Run the following commands from your project folder:
```sh
cd NativeUI
nuget restore
```

### Final steps
Finally, on the root of your project you should see the `packages` folder. Copy that folder and paste it inside of `NativeUI`.

**Comment by Guad** [comment]
I really think this is out of scope and should be on a fork. Especially when I've never used FiveM.

**Comment by justalemon** [comment]
> I really think this is out of scope and should be on a fork.

That is the problem, there a lot of forks and all use the same "NativeUI" name or part of it. Including, but not limited to:

* [NativeUI](https://github.com/citizenfx/NativeUI) CitizenFX edition
* [NativeUI](https://github.com/TomGrobbe/NativeUI) TomGrobbe edition
* [RAGENativeUI](https://github.com/alexguirre/RAGENativeUI)
* [NativeUILua](https://github.com/FrazzIe/NativeUILua)
* [NativeUILua-Reloaded](https://github.com/iTexZoz/NativeUILua-Reloaded)


> Especially when I've never used FiveM.

Don't worry, I use FIveM every day and I can keep this up to date with the master branch.

**Comment by Guad** [comment]
I just think it'd cleaner somewhere like justalemon/NativeUI and then endorsed in the README or something. The issues & PRs would get separated.

**Comment by justalemon** [comment]
We can use labels for that.

Imagine those libraries that have to support multiple frameworks under the same repo. With enough coordination everything stays in peace.

**Comment by Guad** [comment]
Well if you feel like you can manage that, then go ahead 👍

**Comment by manups4e** [comment]
@justalemon why not adding all the features from https://github.com/iTexZoz/NativeUILua-Reloaded ?
it's the most complete lua NativeUI wrapper available.. but not usable by c# and actually i find Guad's the most easy to use versatile in c#.. Great Work u did!!

**Comment by manups4e** [comment]
i would also advice you to use the *official* nuget packages as they get constantly updated

**Comment by justalemon** [comment]
@manups4e We need to decide the package name first, and I might port the rest of elements from the NativeUILua project.

**Comment by manups4e** [comment]
what you mean by package name and way to release it? It's NativeUI what else should it be called?

**Comment by justalemon** [comment]
Currently, we create a Git Tag for each new release. But because we can't have two tags with the same name, we need to find a way to store the code of that release.

For NuGet, we can't use the same package name for the other version. We might try `NativeUI.FiveM` or `NativeUI.CitizenFX`  but that has to be decided with Guad.

**Comment by manups4e** [comment]
At this point I'd suggest you to create your own fork... If you want to
keep it in a branch then its necessary to wait for guard to decide what to
do

Il Gio 21 Mar 2019, 19:34 Hannele Ruiz <notifications@github.com> ha
scritto:

**Comment by manups4e** [comment]
As for the name.. why not NativeUI.fivem

Il Gio 21 Mar 2019, 19:37 Emanuele colecchia <manups4e@gmail.com> ha
scritto:

**Comment by manups4e** [comment]
any news? i'd really need to have all the awesome features this menu could give but doesn't have yet ^^

**Comment by justalemon** [comment]
During the week I'm going to port some of the features.

**Comment by manups4e** [comment]
Awesome!!

Il Lun 1 Apr 2019, 09:09 Hannele Ruiz <notifications@github.com> ha scritto:

**Comment by BobbyTheDev** [comment]
Hmmmm, keeps saying "fatal: not a git repository (or any of the parent directories): .git" when I try to add the command.

**Comment by justalemon** [comment]
Have you created a git repo first? If no, just use git clone -repo-

**Comment by BobbyTheDev** [comment]
Thanks and can you respond to the change menu font I updated it! :hugs:

**Comment by BobbyTheDev** [comment]
Do we just code normally now like basic NativeUI?

**Comment by BobbyTheDev** [comment]
What do you press to open the menu?

**Comment by manups4e** [comment]
@BobbyTheDev that's something you have to code yourself... it's not like MenuApi... this is a different wrapper

**Comment by manups4e** [comment]
any news about newer features?

**Comment by justalemon** [comment]
@manups4e I ended up delaying the port of the new features because we are rewriting some of the classes that impact performance. See #108 for more information.

**Comment by manups4e** [comment]
i saw it :) no problem.. i tried port it myself but with no success XD

**Comment by manups4e** [comment]
any news? i'm impatiently waiting for newer features like heritage window and color panels 😍

**Comment by justalemon** [comment]
Sadly no, I had other projects and programming competitions in progress.

**Comment by manups4e** [comment]
Aaaawww that's ok real life is more important

Il mer 3 lug 2019, 16:48 Hannele Ruiz <notifications@github.com> ha scritto:

**Comment by manups4e** [comment]
hey, i made the pull request for adding some cool features included panels and heritage windows

**Comment by justalemon** [comment]
Due to NativeUI being deprecated (see #135), the recommended thing to do is to use LemonUI NuGet Package. For more information, see the following pages:

* https://github.com/justalemon/LemonUI
* https://www.nuget.org/packages/LemonUI.FiveM/
* https://github.com/justalemon/LemonUI/wiki/Upgrading-from-NativeUI
